#!/usr/bin/env python
"""
Inference script for RS-FLUX RSLayout-DiT
Generate images with layout control using trained LoRA
"""

import argparse
import json
import os
import warnings
from typing import List

import numpy as np
import torch
from diffusers import FluxPipeline
from diffusers.pipelines.flux.pipeline_flux import calculate_shift, retrieve_timesteps
from PIL import Image
from safetensors.torch import load_file

from rslayout_dit.layout_render import render_layout_to_rgb, render_layout_with_labels, LayoutRenderStyle
from rslayout_utils.layout_condition import objects_from_spec, parse_layout_objects
from rslayout_dit.lora_layers import MultiDoubleStreamBlockLoraProcessor, MultiSingleStreamBlockLoraProcessor
import re

warnings.filterwarnings("ignore", message="`FluxPosEmbed` is deprecated.*", category=FutureWarning)


def parse_args():
    parser = argparse.ArgumentParser("Inference with RS-FLUX RSLayout-DiT")

    # Model paths
    parser.add_argument("--pretrained_model_name_or_path", type=str,
                       default="/path/to/FLUX-RS")
    parser.add_argument("--lora_path", type=str, required=True,
                       help="Path to trained LoRA checkpoint (e.g., checkpoint-1000/lora.safetensors)")

    # Input
    parser.add_argument("--layout_json", type=str, default=None,
                       help="JSON file with custom layout")
    parser.add_argument("--data_dir", type=str, default="path_to_data/DIOR/val",
                       help="Data directory for sampling from dataset")
    parser.add_argument("--sample_index", type=int, default=None)
    parser.add_argument("--num_samples", type=int, default=4,
                       help="Number of dataset samples to generate. Use 0 or a negative value for all samples.")
    parser.add_argument("--start_index", type=int, default=0,
                       help="Start metadata index, inclusive, for sharded inference")
    parser.add_argument("--end_index", type=int, default=None,
                       help="End metadata index, exclusive, for sharded inference")
    parser.add_argument("--prompt_metadata_name", type=str, default="metadata_rslayout_prompts.jsonl",
                       help="Optional prompt metadata generated by prepare_rslayout_prompts.py")
    parser.add_argument("--t5_prompt_from_clip_prompt", action="store_true",
                       help="Feed the CLIP/simple prompt to both the CLIP and T5 text encoders.")

    # Generation
    parser.add_argument("--prompt", type=str, default=None,
                       help="Override prompt")
    parser.add_argument("--resolution", type=int, default=512)
    parser.add_argument("--num_inference_steps", type=int, default=28)
    parser.add_argument("--guidance_scale", type=float, default=3.5)
    parser.add_argument("--lora_weight", type=float, default=1.0,
                       help="LoRA weight (0-1, higher = stronger control)")
    parser.add_argument("--multi_scale_condition", action="store_true",
                       help="Use native and coarse layout condition branches for multi-scale LoRA checkpoints.")
    parser.add_argument("--coarse_cond_size", type=int, default=256,
                       help="Downsample size for the coarse multi-scale layout condition before upsampling.")
    parser.add_argument("--disable_causal_mask", action="store_true",
                       help="Ablation: use full bidirectional single-stream attention instead of condition-to-image causal masking.")
    parser.add_argument("--seed", type=int, default=42)

    # Rendering
    parser.add_argument("--render_style", type=str, default="colored_polygons",
                       choices=["colored_polygons", "semantic_map", "edge_map", "heatmap"])
    parser.add_argument("--draw_arrows", action="store_true", default=True)

    # Output
    parser.add_argument("--output_dir", type=str, default="outputs-rslayout-dit")
    parser.add_argument("--save_layout", action="store_true", default=True)
    parser.add_argument("--overwrite", action="store_true",
                       help="Regenerate samples even if output images already exist")
    parser.add_argument("--torch_dtype", type=str, choices=["bf16", "fp16", "fp32"], default="bf16")

    return parser.parse_args()


def load_lora_weights(transformer, lora_path: str, lora_weight: float, cond_size: int, device, dtype, use_causal_mask: bool = True):
    """Load LoRA weights and setup processors"""
    print(f"Loading LoRA from {lora_path}")

    if lora_path.endswith(".safetensors"):
        lora_state_dict = load_file(lora_path, device="cpu")
    else:
        lora_state_dict = torch.load(lora_path, map_location="cpu")

    print(f"Loaded {len(lora_state_dict)} LoRA parameters")

    # Infer LoRA rank and number of condition branches from weights
    rank = None
    n_loras = 1
    for key in lora_state_dict.keys():
        if "down.weight" in key:
            rank = lora_state_dict[key].shape[0]
        match = re.search(r"(?:q|k|v|proj)_loras\.(\d+)\.", key)
        if match:
            n_loras = max(n_loras, int(match.group(1)) + 1)

    if rank is None:
        raise ValueError("Could not infer LoRA rank from checkpoint")

    print(f"LoRA rank: {rank}")
    print(f"Condition LoRA branches: {n_loras}")

    # Setup LoRA processors
    ranks = [rank]
    network_alphas = [rank]
    lora_weights = [lora_weight] * n_loras

    lora_attn_procs = {}
    double_blocks_idx = list(range(19))
    single_blocks_idx = list(range(38))

    for name, attn_processor in transformer.attn_processors.items():
        match = re.search(r'\.(\d+)\.', name)
        if match:
            layer_index = int(match.group(1))
        else:
            layer_index = -1

        if name.startswith("transformer_blocks") and layer_index in double_blocks_idx:
            lora_attn_procs[name] = MultiDoubleStreamBlockLoraProcessor(
                dim=3072,
                ranks=ranks,
                network_alphas=network_alphas,
                lora_weights=lora_weights,
                device=device,
                dtype=dtype,
                cond_width=cond_size,
                cond_height=cond_size,
                n_loras=n_loras,
            )

            # Load weights for this layer
            for i in range(n_loras):
                for proj in ['q', 'k', 'v', 'proj']:
                    down_key = f"{name}.{proj}_loras.{i}.down.weight"
                    up_key = f"{name}.{proj}_loras.{i}.up.weight"
                    if down_key in lora_state_dict:
                        getattr(lora_attn_procs[name], f"{proj}_loras")[i].down.weight.data = lora_state_dict[down_key].to(device=device, dtype=dtype)
                    if up_key in lora_state_dict:
                        getattr(lora_attn_procs[name], f"{proj}_loras")[i].up.weight.data = lora_state_dict[up_key].to(device=device, dtype=dtype)

        elif name.startswith("single_transformer_blocks") and layer_index in single_blocks_idx:
            lora_attn_procs[name] = MultiSingleStreamBlockLoraProcessor(
                dim=3072,
                ranks=ranks,
                network_alphas=network_alphas,
                lora_weights=lora_weights,
                device=device,
                dtype=dtype,
                cond_width=cond_size,
                cond_height=cond_size,
                n_loras=n_loras,
                use_causal_mask=use_causal_mask,
            )

            # Load weights for this layer
            for i in range(n_loras):
                for proj in ['q', 'k', 'v']:
                    down_key = f"{name}.{proj}_loras.{i}.down.weight"
                    up_key = f"{name}.{proj}_loras.{i}.up.weight"
                    if down_key in lora_state_dict:
                        getattr(lora_attn_procs[name], f"{proj}_loras")[i].down.weight.data = lora_state_dict[down_key].to(device=device, dtype=dtype)
                    if up_key in lora_state_dict:
                        getattr(lora_attn_procs[name], f"{proj}_loras")[i].up.weight.data = lora_state_dict[up_key].to(device=device, dtype=dtype)
        else:
            lora_attn_procs[name] = attn_processor

    transformer.set_attn_processor(lora_attn_procs)
    print("LoRA processors setup complete")


def load_samples(args):
    """Load samples from dataset or custom JSON"""
    if args.layout_json:
        with open(args.layout_json, "r") as f:
            spec = json.load(f)
        return [{
            "custom": True,
            "prompt": spec["prompt"],
            "objects": objects_from_spec(spec["objects"]),
            "file_name": "custom"
        }]

    # Load from dataset
    metadata_path = os.path.join(args.data_dir, "metadata.jsonl")
    with open(metadata_path, "r") as f:
        data = [json.loads(line) for line in f if line.strip()]
    for idx, sample in enumerate(data):
        sample["_metadata_index"] = idx

    prompt_metadata_path = os.path.join(args.data_dir, args.prompt_metadata_name)
    if os.path.exists(prompt_metadata_path):
        with open(prompt_metadata_path, "r", encoding="utf-8") as f:
            prompt_records = [json.loads(line) for line in f if line.strip()]
        prompt_by_file = {record["file_name"]: record for record in prompt_records}
        for sample in data:
            record = prompt_by_file.get(sample["file_name"])
            if record:
                sample["clip_prompt"] = record.get("new_clip_prompt")
                sample["t5_prompt"] = record.get("new_t5_prompt")

    if args.sample_index is not None:
        return [data[args.sample_index]]

    start = max(args.start_index, 0)
    end = args.end_index if args.end_index is not None else len(data)
    data = data[start:end]

    if args.num_samples is None or args.num_samples <= 0:
        return data

    import random
    random.seed(args.seed)
    return random.sample(data, k=min(args.num_samples, len(data)))


def main():
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)

    # Setup device and dtype
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    dtype = torch.bfloat16 if args.torch_dtype == "bf16" else \
            torch.float16 if args.torch_dtype == "fp16" else torch.float32

    # Load FLUX pipeline
    print("Loading RS-FLUX pipeline...")
    pipe = FluxPipeline.from_pretrained(args.pretrained_model_name_or_path, torch_dtype=dtype)
    pipe = pipe.to(device)
    pipe.transformer.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    pipe.text_encoder_2.eval()

    # Load LoRA
    load_lora_weights(
        pipe.transformer,
        args.lora_path,
        args.lora_weight,
        args.resolution,
        device,
        dtype,
        use_causal_mask=not args.disable_causal_mask,
    )
    n_loras = 1
    state_dict = load_file(args.lora_path, device="cpu") if args.lora_path.endswith(".safetensors") else torch.load(args.lora_path, map_location="cpu")
    for key in state_dict:
        match = re.search(r"(?:q|k|v|proj)_loras\.(\d+)\.", key)
        if match:
            n_loras = max(n_loras, int(match.group(1)) + 1)
    if n_loras > 1 and not args.multi_scale_condition:
        raise ValueError("This LoRA checkpoint has multiple condition branches; pass --multi_scale_condition.")

    # Load samples
    samples = load_samples(args)
    print(f"Generating {len(samples)} images...")

    # Rendering style
    render_style = LayoutRenderStyle[args.render_style.upper()]

    # Generator
    generator = torch.Generator(device=device).manual_seed(args.seed)

    for idx, sample in enumerate(samples):
        print(f"\n[{idx+1}/{len(samples)}] Processing {sample.get('file_name', 'custom')}")
        output_index = int(sample.get("_metadata_index", idx))
        stem = os.path.splitext(sample.get("file_name", f"sample_{output_index:04d}"))[0]
        stem = f"{output_index:04d}_{stem}"
        generated_path = os.path.join(args.output_dir, f"{stem}_generated.png")
        if os.path.exists(generated_path) and not args.overwrite:
            print(f"Skipping existing output: {generated_path}")
            continue

        # Parse objects
        if sample.get("custom"):
            objects = sample["objects"]
            clip_prompt = sample["prompt"]
            t5_prompt = sample["prompt"]
        else:
            caption = sample["caption"]
            objects = parse_layout_objects(caption, sample["bndboxes"], sample["obboxes"])

            # Build prompt
            from rslayout_utils.prompting import build_satellite_prompts
            built_clip_prompt, built_t5_prompt = build_satellite_prompts(caption, objects)
            clip_prompt = sample.get("clip_prompt") or built_clip_prompt
            t5_prompt = sample.get("t5_prompt") or built_t5_prompt

        if args.prompt:
            clip_prompt = args.prompt
            t5_prompt = args.prompt
        elif args.t5_prompt_from_clip_prompt:
            t5_prompt = clip_prompt

        print(f"CLIP prompt: {clip_prompt}")
        print(f"T5 prompt: {t5_prompt}")
        print(f"Objects: {len(objects)}")

        # Render layout condition
        layout_image = render_layout_to_rgb(
            objects,
            resolution=args.resolution,
            style=render_style,
            draw_arrows=args.draw_arrows,
        )

        # Encode layout to latent
        with torch.no_grad():
            from torchvision import transforms
            transform = transforms.Compose([
                transforms.ToTensor(),
                transforms.Normalize([0.5], [0.5]),
            ])
            layout_tensor = transform(layout_image).unsqueeze(0).to(device, dtype=dtype)

            cond_latents = pipe.vae.encode(layout_tensor).latent_dist.sample()
            cond_latents = (cond_latents - pipe.vae.config.shift_factor) * pipe.vae.config.scaling_factor
            cond_latents_list = [cond_latents]
            if args.multi_scale_condition:
                import torch.nn.functional as F
                coarse_tensor = F.interpolate(
                    layout_tensor.float(),
                    size=(args.coarse_cond_size, args.coarse_cond_size),
                    mode="bilinear",
                    align_corners=False,
                )
                coarse_tensor = F.interpolate(
                    coarse_tensor,
                    size=(args.resolution, args.resolution),
                    mode="bilinear",
                    align_corners=False,
                ).to(dtype=dtype)
                coarse_cond_latents = pipe.vae.encode(coarse_tensor).latent_dist.sample()
                coarse_cond_latents = (
                    coarse_cond_latents - pipe.vae.config.shift_factor
                ) * pipe.vae.config.scaling_factor
                cond_latents_list.append(coarse_cond_latents)

            # Pack condition latents
            packed_cond_latents_list = [
                pipe._pack_latents(item, 1, item.shape[1], item.shape[2], item.shape[3])
                for item in cond_latents_list
            ]
            cond_image_ids_list = [
                pipe._prepare_latent_image_ids(
                    1, item.shape[2] // 2, item.shape[3] // 2, device, dtype
                )
                for item in cond_latents_list
            ]

        # Generate image
        print("Generating...")

        # Note: We need to modify the pipeline call to accept cond_hidden_states
        # For now, we'll use a workaround by directly calling the transformer

        with torch.inference_mode():
            # Encode prompt
            prompt_embeds, pooled_prompt_embeds, text_ids = pipe.encode_prompt(
                prompt=clip_prompt,
                prompt_2=t5_prompt,
                device=device,
                num_images_per_prompt=1,
                max_sequence_length=512,
            )

            # Prepare latents
            latents, latent_image_ids = pipe.prepare_latents(
                1,  # batch_size
                pipe.transformer.config.in_channels // 4,
                args.resolution,
                args.resolution,
                dtype,
                device,
                generator,
            )

            # Denoising loop
            sigmas = np.linspace(1.0, 1 / args.num_inference_steps, args.num_inference_steps)
            if hasattr(pipe.scheduler.config, "use_flow_sigmas") and pipe.scheduler.config.use_flow_sigmas:
                sigmas = None
            mu = calculate_shift(
                latents.shape[1],
                pipe.scheduler.config.get("base_image_seq_len", 256),
                pipe.scheduler.config.get("max_image_seq_len", 4096),
                pipe.scheduler.config.get("base_shift", 0.5),
                pipe.scheduler.config.get("max_shift", 1.15),
            )
            timesteps, _ = retrieve_timesteps(
                pipe.scheduler,
                args.num_inference_steps,
                device,
                sigmas=sigmas,
                mu=mu,
            )

            for t in timesteps:
                combined_latents = torch.cat([latents] + packed_cond_latents_list, dim=1)

                # Prepare timestep
                timestep = t.expand(latents.shape[0]).to(latents.dtype)

                # Prepare guidance
                guidance = torch.tensor([args.guidance_scale], device=device, dtype=dtype).expand(1) \
                           if pipe.transformer.config.guidance_embeds else None

                combined_img_ids = torch.cat([latent_image_ids] + cond_image_ids_list, dim=0)

                # Predict noise
                noise_pred = pipe.transformer(
                    hidden_states=combined_latents,
                    timestep=timestep / 1000,
                    guidance=guidance,
                    pooled_projections=pooled_prompt_embeds,
                    encoder_hidden_states=prompt_embeds,
                    txt_ids=text_ids,
                    img_ids=combined_img_ids,
                    return_dict=False,
                )[0]
                noise_pred = noise_pred[:, :latents.shape[1], :]

                # Scheduler step
                latents = pipe.scheduler.step(noise_pred, t, latents, return_dict=False)[0]

            # Decode latents
            latents = pipe._unpack_latents(latents, args.resolution, args.resolution, pipe.vae_scale_factor)
            latents = (latents / pipe.vae.config.scaling_factor) + pipe.vae.config.shift_factor
            image = pipe.vae.decode(latents, return_dict=False)[0]
            image = pipe.image_processor.postprocess(image, output_type="pil")[0]

        # Save generated image
        image.save(generated_path)

        # Save layout condition
        if args.save_layout:
            layout_image.save(os.path.join(args.output_dir, f"{stem}_layout.png"))

            # Save layout with labels
            layout_labeled = render_layout_with_labels(objects, args.resolution)
            layout_labeled.save(os.path.join(args.output_dir, f"{stem}_layout_labeled.png"))

        # Save prompt
        with open(os.path.join(args.output_dir, f"{stem}_prompt.txt"), "w") as f:
            f.write(f"CLIP: {clip_prompt}\nT5: {t5_prompt}\n")

        print(f"Saved to {args.output_dir}/{stem}_*")

    print(f"\nDone! Generated {len(samples)} images in {args.output_dir}")


if __name__ == "__main__":
    main()
