#!/usr/bin/env python
"""Prompt-only inference for frozen RS-FLUX on DIOR metadata."""

import argparse
import json
import os
from pathlib import Path

import torch
from diffusers import FluxPipeline


def parse_args():
    parser = argparse.ArgumentParser("Prompt-only inference with frozen RS-FLUX")
    parser.add_argument(
        "--pretrained_model_name_or_path",
        type=str,
        default="/path/to/FLUX-RS",
    )
    parser.add_argument("--data_dir", type=str, default="path_to_data/DIOR/test")
    parser.add_argument(
        "--prompt_metadata_name",
        type=str,
        default="metadata_rslayout_prompts.jsonl",
        help="Prompt metadata generated by prepare_rslayout_prompts.py.",
    )
    parser.add_argument("--num_samples", type=int, default=4)
    parser.add_argument("--sample_index", type=int, default=None)
    parser.add_argument("--start_index", type=int, default=0)
    parser.add_argument("--end_index", type=int, default=None)
    parser.add_argument("--prompt", type=str, default=None)
    parser.add_argument("--resolution", type=int, default=512)
    parser.add_argument("--num_inference_steps", type=int, default=28)
    parser.add_argument("--guidance_scale", type=float, default=3.5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output_dir", type=str, default="outputs-text-only-baseline")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--torch_dtype", choices=["bf16", "fp16", "fp32"], default="bf16")
    return parser.parse_args()


def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def load_samples(args):
    metadata_path = Path(args.data_dir) / "metadata.jsonl"
    rows = load_jsonl(metadata_path)
    for idx, row in enumerate(rows):
        row["_metadata_index"] = idx

    prompt_path = Path(args.data_dir) / args.prompt_metadata_name
    if prompt_path.exists():
        prompt_rows = load_jsonl(prompt_path)
        prompt_by_file = {row["file_name"]: row for row in prompt_rows}
        for row in rows:
            prompt_row = prompt_by_file.get(row["file_name"])
            if prompt_row:
                row["clip_prompt"] = prompt_row.get("new_clip_prompt")
                row["t5_prompt"] = prompt_row.get("new_t5_prompt")

    if args.sample_index is not None:
        return [rows[args.sample_index]]

    start = max(args.start_index, 0)
    end = args.end_index if args.end_index is not None else len(rows)
    rows = rows[start:end]

    if args.num_samples is None or args.num_samples <= 0:
        return rows

    return rows[: min(args.num_samples, len(rows))]


def fallback_prompts(row):
    caption = row.get("caption", [])
    labels = [label for label in caption[1:] if label]
    if labels:
        unique = []
        for label in labels:
            if label not in unique:
                unique.append(label)
        objects = ", ".join(unique)
        prompt = f"A satellite image of a remote sensing scene, showing {objects}."
    else:
        prompt = "A satellite image of a remote sensing scene."
    return prompt, prompt


def main():
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)

    dtype = {
        "bf16": torch.bfloat16,
        "fp16": torch.float16,
        "fp32": torch.float32,
    }[args.torch_dtype]
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    print("Loading frozen RS-FLUX pipeline...")
    pipe = FluxPipeline.from_pretrained(args.pretrained_model_name_or_path, torch_dtype=dtype)
    pipe = pipe.to(device)
    pipe.transformer.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    pipe.text_encoder_2.eval()

    samples = load_samples(args)
    print(f"Generating {len(samples)} images...")

    for local_idx, sample in enumerate(samples):
        output_index = int(sample.get("_metadata_index", local_idx))
        image_stem = os.path.splitext(sample.get("file_name", f"sample_{output_index:04d}"))[0]
        stem = f"{output_index:04d}_{image_stem}"
        generated_path = Path(args.output_dir) / f"{stem}_generated.png"
        prompt_path = Path(args.output_dir) / f"{stem}_prompt.txt"

        if generated_path.exists() and not args.overwrite:
            print(f"[{local_idx + 1}/{len(samples)}] Skipping existing output: {generated_path}")
            continue

        clip_prompt = sample.get("clip_prompt")
        t5_prompt = sample.get("t5_prompt")
        if not clip_prompt or not t5_prompt:
            clip_prompt, t5_prompt = fallback_prompts(sample)
        if args.prompt:
            clip_prompt = args.prompt
            t5_prompt = args.prompt

        print(f"\n[{local_idx + 1}/{len(samples)}] Processing {sample.get('file_name')}")
        print(f"CLIP prompt: {clip_prompt}")
        print(f"T5 prompt: {t5_prompt}")

        generator = torch.Generator(device=device).manual_seed(args.seed + output_index)
        with torch.inference_mode():
            image = pipe(
                prompt=clip_prompt,
                prompt_2=t5_prompt,
                height=args.resolution,
                width=args.resolution,
                num_inference_steps=args.num_inference_steps,
                guidance_scale=args.guidance_scale,
                generator=generator,
                max_sequence_length=512,
            ).images[0]

        image.save(generated_path)
        prompt_path.write_text(f"CLIP: {clip_prompt}\nT5: {t5_prompt}\n", encoding="utf-8")
        print(f"Saved to {args.output_dir}/{stem}_*")

    print(f"\nDone! Generated {len(samples)} images in {args.output_dir}")


if __name__ == "__main__":
    main()
